### ISSUE TITLE
uncompress command not passed uncompress directory

### ISSUE THREAD

**Issue by askpatrickw** [wmcbrine/MultiMail#7] opened 2017-12-30 23:43 UTC
MM v0.49
Windows 10
Running MM from the command prompt, not powershell.

When opening a QWK file, the files are not expanded in workNNNN.
They are expanded in the default working directory which may not be multimail's directory.
Would be nice if %2 was the expansion directory [YOUR_PATH]\multimail\workNNN\work

To work around this, I created a mm_unzip.cmd batch file:

```@ECHO OFF
cd [YOUR_PATH]\multimail\work*
..\unzip -joLq %1 -d .\work
```

And set the uncompress command:
```
zipUncompressCommand: [YOUR_PATH]\multimail\mm_unzip.cmd
```

Not sure if there will ever be >1 workNNNN directory but if not, this works.

**Comment by wmcbrine** [comment] 2018-01-17 21:33
Sorry, I can't reproduce the problem you describe.

**Comment by wmcbrine** [comment] 2018-03-20 18:09
Is anyone else seeing this? Any ideas how W7PEA's system (where this happens) might differ from my reference Win 10 system (where it doesn't) that we might be overlooking?

**Comment by wmcbrine** [comment] 2019-03-18 23:06
No followup, can't reproduce, closing.

**Closed as completed by wmcbrine** 2019-03-18 23:06 UTC
